### ISSUE TITLE
Posts don't show up

### ISSUE THREAD

**Issue by Kadoffe** [koca/grav-theme-masonry#1]
Right know my Grav site won't show any posts just an empty white site with the authors name as a headline an the footer. Pagination plugin is installed as well.
Maybe you could provide a complete skeleton so it's easier to figure out what's missing.

Also did you test it with the upcoming v.1.1 of Grav?

**Comment by koca** [comment]
Well, i believe it should work with any kind of blog skeletons in getgrav repos. 
For example:
https://github.com/getgrav/grav-skeleton-mediator-site

### Pages Hierarchy
Under `your/site/user/pages`
```
├── 01.blog (Main folder for blog posts)
│   ├── default.md (blog settings)
|   |── header.jpg (blog cover image if you want to)
|   |
│   ├── post-with-cover (folder for a blog post)
│   │   ├── post.md 
│   │   └── unsplash.jpg
│   ├── tooling-grunt (folder for a blog post)
│   │   └── post.md
|
└── 02.about (Page Folder)
    └── page.md
```

Maybe you are missing default blog settings, under the `your/site/user/pages/blog/default.md` file check/add these lines:

```
---
#cover: header.jpg  this is optional...
sitemap:
    changefreq: weekly
    priority: 1.03
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 8
    pagination: true
feed:
    description: 'Sample Blog Description'
    limit: 3
pagination: true
---

```

I think that should do it let me know if it doesnt or something i'm missing ^^
