### ISSUE TITLE
Author Image not shown

### ISSUE THREAD

**Issue by k1ngf15h3r** [koca/grav-theme-masonry#2]
Hi!

I just installed masonry theme after configuring mediator sceleton, but I can not get my avater shown up. In with folder do I need to place the jpg?

In `user/config/site.yaml` I defined `image: avatar.jpg`

Anything else works great so far. this theme could be the one I will stay on =)

**Comment by koca** [comment]
Hello ^^
Make sure your `user/config/site.yaml` looks like below:
```
# Home Page Title
title: 'Mesut Koca · Web Developer'
description: 'Thoughts, stories and ideas.'

author:
  name: 'Mesut Koca'
  email: youremail@domain.com
  image: avatar.png
```

and you should place the image like so: `your/site/user/themes/masonry/images/avatar.png`
That should do it :)
